# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmultinom_1 <- function(probs, size) {
    .Call(`_LidarLDA_rmultinom_1`, probs, size)
}

samplez1 <- function(theta, phi, y, nclust, npix, nheight, zeroes) {
    .Call(`_LidarLDA_samplez1`, theta, phi, y, nclust, npix, nheight, zeroes)
}

samplez0 <- function(theta, OneMinusPhi, NminusY, nclust, npix, nheight, zeroes) {
    .Call(`_LidarLDA_samplez0`, theta, OneMinusPhi, NminusY, nclust, npix, nheight, zeroes)
}

convertVtoTheta <- function(vmat, prod) {
    .Call(`_LidarLDA_convertVtoTheta`, vmat, prod)
}

ngreater <- function(nlk, npix, nclust) {
    .Call(`_LidarLDA_ngreater`, nlk, npix, nclust)
}

